from kmk.keys import KC

ALL = KC.LCTL(KC.A)
SAVE = KC.LCTL(KC.S)
CUT = KC.LCTL(KC.X)
COPY = KC.LCTL(KC.C)
UNDO = KC.LCTL(KC.Z)
PASTE = KC.LCTL(KC.V)
ALT_TAB = KC.LALT(KC.TAB)

T = KC.TRNS
X = KC.NO

LA_1 = KC.MO(1)
LA_2 = KC.MO(2)
